CREATE TABLE person
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  VARCHAR(100)                            NOT NULL,
    last_name   VARCHAR(100)                            NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    dateofbirth date                                    NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT pk_person PRIMARY KEY (id)
);